"""agregar telefono secundario a clientes

Revision ID: 63a05c11332d
Revises: 714e69f80a08
Create Date: 2026-06-28 16:10:25.784949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63a05c11332d'
down_revision: Union[str, Sequence[str], None] = '714e69f80a08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('telefono_secundario', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'telefono_secundario')
    # ### end Alembic commands ###
