"""eliminar telefono secundario de clientes

Revision ID: 98923d16f4e8
Revises: 63a05c11332d
Create Date: 2026-06-30 11:37:06.970226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98923d16f4e8'
down_revision: Union[str, Sequence[str], None] = '63a05c11332d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veterinarios_id'), table_name='veterinarios')
    op.drop_table('veterinarios')
    op.drop_column('clientes', 'telefono_secundario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clientes', sa.Column('telefono_secundario', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.create_table('veterinarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('especialidad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefono', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('veterinarios_pkey'))
    )
    op.create_index(op.f('ix_veterinarios_id'), 'veterinarios', ['id'], unique=False)
    # ### end Alembic commands ###
